#! /bin/bash

#- ---------------------------------------------------------------------------
#-    Copyright (C) 2017 - Institut Curie
#-
#- This file is a part of Raw-qc software.
#-
#- File author(s):
#-     Dimitri Desvillechabrol <dimitri.desvillechabrol@curie.fr>
#- 
#- Distributed under the terms of the CeCILL-B license.
#- The full license is in the LICENSE file, distributed with this
#- software.
#- ---------------------------------------------------------------------------

## ---------------------------------------------------------------------------
## Basic_metrics
##
## Wrapper of Basic_metrics with many sanity check.
## A simple tool to calculate basic stats of a sample.
## 
## Inputs:
##      - String $INPUT: Input FastQ file(s) and JSON file generated by autotropos.
##      - String $OUTPUT: Output JSON file for basic_metrics.
##      - String $CONFIG: JSON configuration file.
##      - String $LOG: Log file.
## ---------------------------------------------------------------------------

# Import utils
path="${BASH_SOURCE[0]%/*}/"
. "${path}"utils-bash.sh

# Initiate variable of the wrapper ($INPUT, $OUTPUT, $CONFIG, $LOG)
init_wrapper $@

# Catch variable in json
basic_metrics_path="$(get_json_entry ".basic_metrics.path" ${CONFIG})"
basic_metrics_option="$(get_json_entry ".basic_metrics.options" ${CONFIG})"
basic_metrics_threads="$(get_json_entry ".basic_metrics.threads" ${CONFIG})"

if [[ -n "${basic_metrics_path}" ]]; then
    basic_metrics_path="${basic_metrics_path%/}/"
fi

# add ID name in outputs, inputs and logs
inputs=($INPUT)
create_directory ${OUTPUT%/*}
create_directory ${LOG%/*}

# set some local variable
line=("${inputs[0]}")
basic_metrics_json=("--json" "${inputs[1]}")
IFS=',' read -r -a sample_array <<< "$line"
sample_id=${sample_array[0]}
sample_name=${sample_array[1]}
raw_fastq=(${sample_array[@]:2:2})
basic_metrics_fastq=(-1 ${raw_fastq[0]})
if [[ ${#raw_fastq[@]} -eq 2 ]]; then
    basic_metrics_fastq+=(-2 ${raw_fastq[1]})
fi

_fail=0 # variable to check if everything is ok

# Command line
cmd="${basic_metrics_path}fastq_basic_metrics ${basic_metrics_option} \
                            ${basic_metrics_fastq[@]} \
                            ${basic_metrics_json[@]} \
                            -p ${OUTPUT} \
                            -i ${sample_id} \
                            -s ${sample_name}"
$cmd > ${LOG} 2>&1 || _fail=1

exit ${_fail}
